### ISSUE TITLE
Morning Session #5 Week 4 Module I : Peer to peer code review

### ISSUE THREAD

**Issue by Hannziegel** [jaferIdrees/Portfolio-Project_Microverse#14]
Hi, @jaferIdrees  😄 : 
![](https://c.tenor.com/-SRHVNXqVVsAAAAC/skoda-enyaq.gif) 

Your Portfolio Project is looking great! :sunglasses: Although we have found some room for improvement that could make your project look more professional.

### Optional Suggestions for form javascript local storage 

- [ ] In the future when you have some time it would be great if you added a feature that resets the local storage for the message when the email is sent. In this way, if the people who want to send you another email they will only have to change the message, and it will not send a copy of the email again
- [ ] Another way to do your function is instead of using 'change' that checks every alteration, you can use the input to check the input part for alterations. This is an optional suggestion, you can see what do you think is best for your project

**Comment by jaferIdrees** [comment]
Many thanks for your valuable comments.
